### ISSUE TITLE
When trying to use AuraSR, extension throws an error: AttributeError: 'AuraSR' object has no attribute 'to'

### ISSUE THREAD

**Issue by Sana-A-E** [AndreyRGW/sd-webui-aurasr#2]
Upon trying to use the extension from Extras tab it throws the following error nearly immediately after start and doesn't produce a result:
```
Traceback (most recent call last):
      File "\Automatic1111 WebUI\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "\Automatic1111 WebUI\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "\Automatic1111 WebUI\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "\Automatic1111 WebUI\modules\postprocessing.py", line 133, in run_postprocessing_webui
        return run_postprocessing(*args, **kwargs)
      File "\Automatic1111 WebUI\modules\postprocessing.py", line 73, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "\Automatic1111 WebUI\modules\scripts_postprocessing.py", line 198, in run
        script.process(single_image, **process_args)
      File "\Automatic1111 WebUI\scripts\postprocessing_upscale.py", line 152, in process
        upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, max_side_length, upscale_to_width, upscale_to_height, upscale_crop)
      File "\Automatic1111 WebUI\scripts\postprocessing_upscale.py", line 107, in upscale
        image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
      File "\Automatic1111 WebUI\modules\upscaler.py", line 68, in upscale
        img = self.do_upscale(img, selected_model)
      File "\Automatic1111 WebUI\extensions\sd-webui-aurasr\scripts\aurasr_upscaler.py", line 28, in do_upscale
        return runAuraSR(img, device)
      File "\Automatic1111 WebUI\extensions\sd-webui-aurasr\scripts\aurasr_tools.py", line 17, in runAuraSR
        aura_sr = get_aura_sr_model(device)
      File "\Automatic1111 WebUI\extensions\sd-webui-aurasr\scripts\aurasr_tools.py", line 12, in get_aura_sr_model
        return model.to(device)
    AttributeError: 'AuraSR' object has no attribute 'to'
```

Just posting in case someone else runs into this error or in case there is something obvious I am missing that can easily be fixed.

**Comment by AndreyRGW** [comment]
Try updating the extension and see if the error persists or not.

**Comment by Sana-A-E** [comment]
It works now, thank you very much.
